version: "3.8"

services:
  app:
    image: therealjensjk/studyfront:Backend
    container_name: studyfront-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT:-5000}
      - MONGO_URI=${MONGO_APP_URI:-mongodb://mongo:27017/studyfront}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: therealjensjk/studyfront:Database
    container_name: studyfront-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: