version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: studyfront-backend
    container_name: studyfront-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/studyfront
      - JWT_SECRET=superSecretKey
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: